wandb_version: 1

input_dim:
  desc: null
  value: 784
hidden_dim:
  desc: null
  value: 500
latent_dim:
  desc: null
  value: 5
batch_size:
  desc: null
  value: 100
epochs:
  desc: null
  value: 30
lr:
  desc: null
  value: 0.01
best_loss:
  desc: null
  value: 1000000000
patience_limit:
  desc: null
  value: 3
_wandb:
  desc: null
  value:
    python_version: 3.9.18
    cli_version: 0.15.12
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1697547975.716671
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 2
      - 16
      - 23
      4: 3.9.18
      5: 0.15.12
      8:
      - 1
      - 3
      - 5
      13: windows-amd64
