wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.19
    cli_version: 0.17.8
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1725260518
    t:
      1:
      - 1
      - 55
      3:
      - 15
      - 23
      4: 3.9.19
      5: 0.17.8
      6: ''
      8:
      - 3
      - 5
      12: ''
      13: windows-amd64
