wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.19
    cli_version: 0.17.8
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1725258434
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 2
      - 15
      - 23
      4: 3.9.19
      5: 0.17.8
      6: ''
      8:
      - 3
      - 5
      12: ''
      13: windows-amd64
seed:
  desc: null
  value: 0
dataset:
  desc: null
  value: MNIST
hidden_dim:
  desc: null
  value:
  - 32
  - 64
  - 128
latent_dim:
  desc: null
  value: 128
batch_size:
  desc: null
  value: 64
lr:
  desc: null
  value: 0.005
weight_decay:
  desc: null
  value: 0.0
scheduler_gamma:
  desc: null
  value: 0.95
kld_weight:
  desc: null
  value: 0.00025
epochs:
  desc: null
  value: 100
